// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjccHpWWaJswzvyzoQvLIfFUanQalFyn8',
    appId: '1:913236770657:web:346598e4926fda94fb4f20',
    messagingSenderId: '913236770657',
    projectId: 'miaged-49038',
    authDomain: 'miaged-49038.firebaseapp.com',
    storageBucket: 'miaged-49038.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4UNyqHe1Rp8F1gqe7GFompyYk7mh3WqM',
    appId: '1:913236770657:android:b4964b22c7a74822fb4f20',
    messagingSenderId: '913236770657',
    projectId: 'miaged-49038',
    storageBucket: 'miaged-49038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo-P0nNXGwPrDCsZojVrfHSg1qUokReW4',
    appId: '1:913236770657:ios:84751bcfd48f3dd0fb4f20',
    messagingSenderId: '913236770657',
    projectId: 'miaged-49038',
    storageBucket: 'miaged-49038.appspot.com',
    iosClientId: '913236770657-othgekqhv6srtshvgg784rs1iel6ngt4.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.miaged',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo-P0nNXGwPrDCsZojVrfHSg1qUokReW4',
    appId: '1:913236770657:ios:84751bcfd48f3dd0fb4f20',
    messagingSenderId: '913236770657',
    projectId: 'miaged-49038',
    storageBucket: 'miaged-49038.appspot.com',
    iosClientId: '913236770657-othgekqhv6srtshvgg784rs1iel6ngt4.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.miaged',
  );
}
